zap:
  debugFileName: "D:\\git-demo\\ms-project\\logs\\debug\\project-debug.log"
  infoFileName: "D:\\git-demo\\ms-project\\logs\\info\\project-info.log"
  warnFileName: "D:\\git-demo\\ms-project\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
server:
  name: "project-api"
  addr: "127.0.0.1:8080"
etcd:
  addrs:
    - "127.0.0.1:2379"